### ISSUE TITLE
can not see install button azure data studio marketplace

### ISSUE THREAD

**Issue by minhazrwe** [yterterian/In-Query-Generator-AZ#1]
There is no button call install or VSIX file in Azure data studio marketplace
![Screenshot 2024-11-21 160818](https://github.com/user-attachments/assets/af8a03a1-9d0a-40a0-834c-42cb75a90d99)

**Comment by yterterian** [comment]
Hi @minhazrwe, 

Please note that this is a Microsoft limitation.
- We currently don't have support to host third-party extensions. Instead of downloading the extension, Azure Data Studio has the option to browse to a download page. To set a download page for your extension, set the value of the asset Microsoft.AzureDataStudio.DownloadPage.
